---
- hosts: all
  become: yes
  become_user: root
  vars:
    arch_mapping: 
      x86_64: amd64
      aarch64: arm64

  tasks:
    # --------------------------------------------------------------
    # Upgrade/Update Server
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes
    
    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the Servers (if required)
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
    
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes

    # -------------------------------------------------------------
    # NFS Common Packages
    - name: Install NFS Common Packages    
      ansible.builtin.apt:
        name: nfs-common
        state: present

    # -------------------------------------------------------------
    # Install Docker
    - name: Remove Any Conflicting Packages
      ansible.builtin.apt:
        name:
        - docker.io
        - docker-dock
        - docker-compose
        - docker-compose-v2
        - podman-docker
        - containerd
        state: absent

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common

    - name: Create directory for Docker's GPG Keys
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service