---
- name: Perform Game Server Updates And AMP Instance Manager Upgrade
  hosts: all
  become: true
  become_user: root # Default for the play

  tasks:
    # --- ROOT User Tasks ---
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes
    
    # --- AMP User Tasks (Grouped in a Block) ---
    - name: AMP Instance Manager Upgrade Tasks
      block:
        - name: Execute ampinstmgr upgradeall without cache
          ansible.builtin.command: ampinstmgr --nocache upgradeall
      become_user: amp # This applies only to the tasks within this block

    # --- ROOT User Tasks ---
    - name: Reboot the Servers
      ansible.builtin.reboot:
      
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes